### ISSUE TITLE
Flow origin option resets when switching from plot to map

### ISSUE THREAD

**Issue by qdread** [qdread/biodiversity-farm2fork#18]
After PR #16 merged, now if you switch from plot tab to map tab, flow origin resets to domestic even if foreign is selected (foreign is valid for the map tab so it would be great if that would not reset). thanx!

**Comment by khondula** [comment]
woops, didn't even think to check that!

**Comment by qdread** [comment]
I guess the way to fix it is just to add `selected = ` arguments to the different `switch` radio button menus on lines 129-131?

**Comment by qdread** [comment]
Resolved this in 5adfebe (I also reindented all the code in that commit so basically every line changed)
